language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp
script:
- npm install
- gulp lint
- [[ "$TRAVIS_BRANCH" = "master" ]] && gulp commit
- [[ "$TRAVIS_BRANCH" = "stable" ]] && gulp commit
before_install:
- openssl aes-256-cbc -K $encrypted_0edb3429ae38_key -iv $encrypted_0edb3429ae38_iv
  -in credentials.json.enc -out credentials.json -d
