language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp
script:
- "npm install"
- "gulp lint"
- "if [[ $TRAVIS_BRANCH = master ]]; then gulp commit; fi"
- "if [[ $TRAVIS_BRANCH = stable ]]; then gulp commit; fi"
before_install:
- "if [[ $TRAVIS_PULL_REQUEST = false ]]; then openssl aes-256-cbc -K $encrypted_0edb3429ae38_key -iv $encrypted_0edb3429ae38_iv
  -in credentials.json.enc -out credentials.json -d; fi"
